language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
services: 
  - mongodb
before_script:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/coveralls
